### ISSUE TITLE
SayDialog Typing Animation starts at wrong Position when using TMP

### ISSUE THREAD

**Issue by Tintifax69** [snozbot/fungus#954] opened 2021-02-01 15:47 UTC
**Describe the bug**
When using a custom SayDialog that uses a TextMeshPro - Text (UI) the Typing Animation starts with the text already half/comletely finished.
Meaning a portion of the Text or the whole Text is already there and the Typing Animation only finishes the rest of the Text.
This only seems to happen when the Say Command is called after a Menu Command. However it does not have to be called directly by the Menu Command.
When using two Say Commands in succession the second one will always properly start at the beginning of the text.

**To Reproduce**
1. Create a custom SayDialog that uses a TMP text component instead of the standard unity text component.
3. Create a Flowchart with a Say Command that uses the custom SayDialog.
4. Call the Block with the Say Command via a Menu Command repeatedly (does not always happen on first time)

**Expected behavior**
The Typing Animation in a SayDialog should always start with an empty Text component

**Versions & Platform (please complete the following information):**
 - Unity version 2020.2.1f1
 - Fungus Version v.3.13.6
 - Editor OS: Win 10
 - Build Platform: Windows Standalone
 - TextMeshPro: 3.0.1

**Comment by breadnone** [comment] 2021-02-01 16:00
@Tintifax69 I made a pr for this issue https://github.com/snozbot/fungus/pull/952

**Comment by TheEmbracedOne** [comment] 2021-03-27 20:30
This is related to #910 - see that post for some gif demonstrations and my reproduction @stevehalliwell 

I'll try the pr by @breadnone  (thank you!) and report back whether if tixed the issue on my end too!

**Comment by stevehalliwell** [comment] 2021-06-12 04:03
Potentially a duplicate of #910

**Comment by stevehalliwell** [comment] 2021-06-14 08:07
#985 reportedly does solve #910, moving forward and assuming the same is true here. Please feel free to reopn the issue if that turns out not to be the case.

**Closed by stevehalliwell** 2021-06-14 08:07 UTC
Labels: bug
